### ISSUE TITLE
IMPLEMENT: Firebase Authentication 

### ISSUE THREAD

**Issue by admin-vbsquad** [VBSquad/Androiders-Buddy#100]
**Implement:** Firebase Authentication

**Type:** UI XML & java

**Context:** Create an Android app showcasing the implementation of Firebase Login and Register Authentication.

**Comment by rahullli** [comment]
I would like to work on this issue .

**Comment by admin-vbsquad** [comment]
> I would like to work on this issue .

Actually someone has already sent his PR before so I can't assign you this issue. You can create more issues by yourself and then get yourself assigned.
