### ISSUE TITLE
IMPLEMENT: Android Notification

### ISSUE THREAD

**Issue by admin-vbsquad** [VBSquad/Androiders-Buddy#104]
**Implement:** Android Notification

**Type:**  Java

**Context:** Create an Android app showing how you can implement the Android Notifications in your app. You can use the _**NotificationCompat.Builder**_ object.

**Comment by Dhruv-194** [comment]
Can you please assign it to me?

**Comment by admin-vbsquad** [comment]
> Can you please assign it to me?

Yes you can take it but complete it within 24hrs otherwise we will assign it someone else.
