### ISSUE TITLE
IMPLEMENT: Android TextToSpeech

### ISSUE THREAD

**Issue by admin-vbsquad** [VBSquad/Androiders-Buddy#107]
**Implement:** Android TextToSpeech

**Type:** UI XML & Java

**Context:** Create an Android app demonstrating how will you implement the Android TextToSpeech function in your app. You can convert your text into speech by the help of **TextToSpeech class**.

**Comment by Dhruv-194** [comment]
Can you please assign this to me?

**Comment by AntoineDoniel** [comment]
can i be assigned to this?
