### ISSUE TITLE
Add hyperlinks 

### ISSUE THREAD

**Issue by admin-vbsquad** [VBSquad/Androiders-Buddy#110]
**Add hyperlinks to all UI/Widgets and Java related topic in readme which will direct to that specific folder.**

For reference you can see the section : The UI/Widgets related topics: "CustomToast" that have hyperlink that directs to https://github.com/VBSquad/Androiders-Buddy/tree/master/UI%20XML/CustomToast .

**Comment by admin-vbsquad** [comment]
@daniel-shuy before sending pr's you need to get issue assigned first,  Also in PR you havent added hyperlinks in Java section. Do the needful to get pr merged.

**Comment by daniel-shuy** [comment]
> before sending pr's you need to get issue assigned first

sorry, didn't notice the Contribution section, please assign the issue to me, thanks!

> Also in PR you havent added hyperlinks in Java section

oops sorry, somehow I didn't see the Java section, I'll add them as well

Also, I noticed there are a few topics in the `README` that do not correspond to any folder, should I just ignore them or should I update the `README` (to remove them and to add topics that are not listed)?

**Comment by admin-vbsquad** [comment]
@daniel-shuy  ignore that topic in readme . we will create new issues for those topics

**Comment by daniel-shuy** [comment]
Alright, I've updated the PR to include Java coding topics
