### ISSUE TITLE
IMPLEMENT: AlertDialog

### ISSUE THREAD

**Issue by Dhruv-194** [VBSquad/Androiders-Buddy#21]
**Implement:** AlertDialog

**Type:** UI XML  

**Context:** Create an Android app demonstrating the use of Alert Dialog by displaying dialog messages with suitable action button options.

**Comment by JyotiJauhari** [comment]
Please assign me this issue. @Dhruv-194

**Comment by jyotijauhari** [comment]
Please assign me this issue
