### ISSUE TITLE
IMPLEMENT: Spinner

### ISSUE THREAD

**Issue by Dhruv-194** [VBSquad/Androiders-Buddy#22]
**Implement:** Spinner

**Type:** UI XML

**Context:** Create an Android app demonstrating the use of Spinner to display mutliple drop-down options and an action which happens on chossing anyone of them.

**Comment by JyotiJauhari** [comment]
Please assign me this issue @Dhruv-194

**Comment by jyotijauhari** [comment]
Please assign me this issue
