### ISSUE TITLE
IMPLEMENT: AutoCompleteTextView

### ISSUE THREAD

**Issue by Dhruv-194** [VBSquad/Androiders-Buddy#23]
**Implement:** AutoCompleteTextView

**Type:** UI XML 

**Context:** Create an app showcasing AutoCompleteTextView in which an edit text completes the entered user text based on the reserved words.

**Comment by JyotiJauhari** [comment]
Please assign me this issue. @Dhruv-194

**Comment by jyotijauhari** [comment]
Please assign me this issue
