### ISSUE TITLE
IMPLEMENT: Toast

### ISSUE THREAD

**Issue by Dhruv-194** [VBSquad/Androiders-Buddy#3]
**Implement:** Toast

**Type:** XML and Java 

**Context:** Create an Android app showcasing the use of Toasts in any form.

**Comment by vatsalkesarwani12** [comment]
please assign it to me

**Comment by vatsalkesarwani12** [comment]
@Dhruv-194 sir where should we add this issue java or ui xml??

**Comment by Dhruv-194** [comment]
@plazzy99 as this topic is mentioned in the list of UI XML in the Readme file therefore commit it into the UI XML folder only.
