### ISSUE TITLE
IMPLEMENT: ImageSlider

### ISSUE THREAD

**Issue by Dhruv-194** [VBSquad/Androiders-Buddy#46]
**Implement:** ImageSlider

**Type:** UI XML 

**Context:** Create an app showcasing the use of ImageSlider which slides an entrie screen to another screen.

**Comment by jyotijauhari** [comment]
PLEASE assign it to me.

**Comment by jyotijauhari** [comment]
> **Implement:** ImageSlider
> 
> **Type:** UI XML
> 
> **Context:** Create an app showcasing the use of ImageSlider which slides an entrie screen to another screen.



> PLEASE assign it to me.
