### ISSUE TITLE
IMPLEMENT: TabLayout with FrameLayout

### ISSUE THREAD

**Issue by Dhruv-194** [VBSquad/Androiders-Buddy#49]
**Implement:** TabLayout with FrameLayout

**Type:** UI XML 

**Context:** Create an app demonstrating the use of TabLayout with FrameLayout by creating non sliding tabs. Feel free to position them either at the bottom of the screen or on top of the screen.

**Comment by vatsalkesarwani12** [comment]
please assign it to me
