### ISSUE TITLE
IMPLEMENT: SearchView

### ISSUE THREAD

**Issue by Dhruv-194** [VBSquad/Androiders-Buddy#50]
**Implement:** SearchView

**Type:** UI XML  

**Context:** Create an Android app demonstrating the use of SearchView widget which searches items added in a custom list. Use the two methods - _**public boolean onQueryTextSubmit(String query)**_ & _**public boolean onQueryTextChange(String newText)**_

**Comment by jyotijauhari** [comment]
PLEASE assign it to me.

**Comment by jyotijauhari** [comment]
@Dhruv-194 can you tell once how to make a folder in this java type issue.

**Comment by Dhruv-194** [comment]
> @Dhruv-194 can you tell once how to make a folder in this java type issue.

You have to create three seperate file folder in the assigned topic folder, in the same way as you were doing before. Now as these are core Java topics, I have made a Main Java folder in the repo so add these file and folders to that Main Java folder. Everything remains the same, you just need to add that topic folder with all the files in Main Java folder.
