### ISSUE TITLE
IMPLEMENT: Activity LifeCycle

### ISSUE THREAD

**Issue by Dhruv-194** [VBSquad/Androiders-Buddy#55]
**Implement:** Activity LifeCycle

**Type:**  Java 

**Context:** Create an Android app which correctly demonstrates the seven lifecycle methods of android activity.

**Comment by vatsalkesarwani12** [comment]
Please assign it to me

**Comment by vatsalkesarwani12** [comment]
@Dhruv-194  can you tell once how to make a folder in this java type issue.

**Comment by Dhruv-194** [comment]
> @Dhruv-194 can you tell once how to make a folder in this java type issue.

You have to create three seperate file folder in the assigned topic folder, in the same way as you were doing before. Now as these are core Java topics, I have made a Main Java folder in the repo so add these file and folders to that Main Java folder. Everything remains the same, you just need to add that topic folder with all the files in Main Java folder.
